
-- imagename in the below table is the unique name generated by crypto
CREATE TABLE image (imageName TEXT UNIQUE NOT NULL);
CREATE TABLE contact (id SERIAL PRIMARY KEY, name TEXT, number TEXT, email TEXT, message TEXT);
